[package]
name = "cocktail"
version = "0.1.0"
authors = ["Pierre Marijon <pmarijon@mpi-inf.mpg.de>"]
edition = "2018"

[lib]
name = "cocktail"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]

[dev-dependencies]
rand      = "0.7"
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
